version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crud_produto
    volumes:
      - /tmp/database:/var/lib/postgresql/data
    restart: unless-stopped
